version: '3.9'


services:
  postgres:
    container_name: courtrecort_db
    image: postgres:latest
    environment:
      POSTGRES_USER: courtrecord
      POSTGRES_PASSWORD: P@ssw0rd
      PGDATA: courtrecord
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5402:5432"


volumes:
  postgres-db:
    driver: local